name: drag_and_drop_reorderable_lists
description: "Customizable drag & drop widgets in lists with reordering."
version: 0.1.5
homepage: https://github.com/sergiofdezp/drag_and_drop_reorderable_lists
repository: https://github.com/sergiofdezp/drag_and_drop_reorderable_lists
issue_tracker: https://github.com/sergiofdezp/drag_and_drop_reorderable_lists/issues

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true